---
title: "Scratching an itch"
description: "When there's no one to please"
author: "Renato Vargas"
date: "2025-11-19"
categories:
  - life
  - social media
---

The data science community is very generous. It seems like everybody is eager to share how to best accomplish something. About a year or two ago, I started a LinkedIn newsletter called "Tools for Consultants," which has some 270 subscribers. After a few posts, I soon realized that my posts only had about 6 to 12 "reactions," mostly from people who reacted because they care about me on a personal level. Supportive friends or former colleagues. However, there was no engagement. I even tried asking questions at the end of the posts and nothing. And this is something that appears to be common. A lot of interesting people have websites full of material no one cares about. I think that there's a lot of "so what" in what we find interesting ourselves and the niches are not big enough to develop an audience. 

On the other hand, though, I see these made up situation posts from people that go something like "I recently heard so and so say" followed by something like, but "here's THE TRUTH," and you know they never heard anybody say anything, they just needed that fake situation to set up the point they want to make. Another one is "I am constantly asked..." followed by [INSERT CORPORATE NON-ADVICE ADVICE]. You know nobody's asked them anything either. The thing is that those kinds of sleazy posts get thousands of reactions and hundreds of comments.

That's why I decided to write this blog for an audience of one. This is a blog to exercise my writing muscle and to reflect on the things I find interesting. Not because I want to develop my "authority" status or anything like that. I am hoping that that will result in more focus on things that matter and noth things that might have better engagement. 

_Any typos you find here are actually on purpose._
