---
title: "Guaranteed Human"
description: "There are some thin"
author: "Renato Vargas"
date: "2025-12-03"
categories:
  - life
---

I have been a listener of the Revisionist History podcast since its inception and their partner iHeartMedia recently they added a slogan in which a femenine voice says "Guaranteed Human". According to the Los Angeles Times "The marketing push capitalizes on (...) a desire for authentic human connection amid rapidly changing media." And as a listener, I'd say the move works. Human is evident and it is worth so much more than the alternative.

This week I also came across "The Moth Radio Hour", which is a podcast that features community-focused, open-mic storytelling competitions in which anyone can share a five-minute story on the night’s theme. I heard five beautiful deeply personal stories that made me laugh so hard and cry my eyes out in the course of a few minutes. I said to myself "we will be fine, nothing artificial will ever replace this".

We discussed with a friend that what makes us valuable are not our R programming skills, but our combined 50 years of experience in our field, understanding things that go beyond the code or the analysis technique. Yes, we will continue to update our skills and take advantage of new technologies, but nothing will replace our humanity. 

Guaranteed Human indeed.

_Any typos you find here are actually on purpose._


