---
title: "Renato Vargas | Economist"
---

Over 20 years of experience researching, writing, and speaking about the link between economics, environmental sustainability and social issues. With a demonstrated history of helping **Task Team Leaders** and **Project Managers** from organizations, such as **The World Bank**, the **United Nations Economic Commission for Latin America and the Caribbean**, and the **Inter-American Development Bank**, create data-backed and science-based top quality economic research to persuade clients, disseminate ideas among stakeholders, back institutional goals, and provide support for public and private policies.

I am available on a Short Term (STC), Extended Term (ETC), or Services Rendered contractual basis. Please reach out via:

<a class="btn btn-primary btn-lg" href="https://www.linkedin.com/in/revargas/" role="button"> LinkedIn </a>
<a class="btn btn-success btn-lg" href="https://wa.me/50251556635" role="button">WhatsApp</a>


**I specialize in:**

<div class="alert alert-light" role="alert">
  <h4 class="alert-heading">**Environmental Accounts | Bioeconomy Assesment**</h4>
  <p>Environmentally-Extended Macroeconomic-Accounting analysis, based on the principles of the **System of Environmental and Economic Accounts (SEEA)**.</p>
</div>

<div class="alert alert-primary" role="alert">
  <h4 class="alert-heading">**Household Survey Analysis | Poverty Assessment**</h4>
  <p>I analyze the effects of climate-induced risks on income and expenditure distributions at the regional level with advanced household survey analysis in **R** or **Stata**.</p>
</div>

<div class="alert alert-light" role="alert">
  <h4 class="alert-heading">**General Equilibrium Modeling**</h4>
  <p>Trained in the use of models like **GTAP, IEEM,** and the **PEP** family of models for environmentally-extended economic analysis and the energy transition.</p>
</div>

<div class="alert alert-primary" role="alert">
  <h4 class="alert-heading">**Environmentally-Extended Input-Output Modeling**</h4>
  <p>Developed an environmentally-extended macroeconomic analysis framework for rapid policy impact analysis in **R** or **Excel**.</p>
</div>

<div class="alert alert-light" role="alert">
  <h4 class="alert-heading">**Ecosystem Service and Land Use Change Modeling**</h4>
  <p> Experience in the implementation of the InVEST suite of ecosystem service modeling tools and the use of S-CLUE to model Land Use Land Cover change. Ample experience in Geographic Information Systems.</p>
</div>

<div class="alert alert-primary" role="alert">
  <h4 class="alert-heading">**Data Management and Data Analysis**</h4>
  <p>With a thorough understanding of data analytical tools and experience in monitoring and evaluation, I leverage programming environments like **R, Python, GAMS, GEMPACK,** and **Stata**, as well as **Quarto, RShiny, Tableau, and PowerBI** among others, to create analytical products, databases and dashboards for analysis projects and flagship reports.</p>
</div>

<div class="alert alert-light" role="alert">
  <h4 class="alert-heading">**Technical writing**</h4>
  <p>I have two decades of experience writing flagship reports, scientific papers, policy notes, and dissemination articles on sustainability and environmentally-extended economic analysis for different audiences, including policy-makers, technical staff, academics, and the general public.</p>
</div>

<div class="alert alert-primary" role="alert">
  <h4 class="alert-heading">**Training and Dissemination**</h4>
  <p>I provide specialized training in macroeconomic data management and analysis for policy design and evaluation teams, using a hands-on, learning-by-doing approach. I deliver presentations at international forums to disseminate research outcomes and policy recommendations.</p>
</div>





