---
title: "A flagship product"
description: "On meaningful work"
author: "Renato Vargas"
date: "2025-11-27"
categories:
  - life
  - projects
---

I've talked about Omarchy and Ruby On Rails, two projects that don't have a lot to do with Data Science, or not obviously at least. Alright, I know that Omarchy could be a data scientist's operating system of choice and that Rails was used to develop GitHub originally, but they aren't inherently data science oriented. What they have in common is that the original developer behind them is David Heinemeier Hansson, or DHH, as he is known.

I became aware of Omarchy recently, when YouTube suggested a video of the Rework podcast from 37signals, which is his company's very honest way of working publicly. But this way of showing what they are working on is not a new endeavor for them. In the late 2000s and early 2010s there was the 37signals blog _Signal vs. Noise_ and a couple of books on work culture called _Remote_ and _Rework_. I was a big fan even then. They had disappeared from my radar, though. 

Re-encountering them was very satisfying, because DHH and Jason Fried, his business partner, along with Kimberly Rhodes, who hosts the podcast, explore very interesting topics around work culture with the backdrop of their own very successful technology projects. And you can really see the excitement that they have for these products. It's contagious. After listening to DHH describe Omarchy, or the new features of Rails, cussing and everything, you just feel like you want him to lead you into battle with Omarchy and Rails as your sword and shield.

It is a passion I am looking forward to having and that is why I am now on the lookout for that next passion project for myself; that thing that will consume every idle moment I have; that I can be proud of; that will cause others to be excited too. I don't know what it is yet, but I can feel it coming.

_Any typos you find here are actually on purpose._


